name = "ToddlerED"
uuid = "9f6f0ab1-6019-4add-889f-74609d4bcb4c"
authors = ["Yang Ge"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
